export default {
  supportBetaTemplatesList: false,
  supportBetaUsers: false,
  supportBetaUserProfile: false,
  supportBetaSettings: false,
  supportBetaLogin: false,
  supportBetaTeamCreate: true,
  supportBetaTeamEdit: true,
  supportBetaTeamView: true,
  supportBetaPropertiesList: true,
  supportBetaPropertyProfile: true,
  supportBetaPropertyCreate: true,
  supportBetaPropertyDeficient: false,
  supportBetaPropertyYardiResident: false,
  supportBetaPropertyYardiWorkOrder: false,
  supportBetaPropertyInspectionCreate: true,
  supportBetaPropertyInspectionUpdate: false,
  supportBetaPropertyInspectionMove: false,
  supportBetaPropertyUpdate: true,
  supportBetaInspectionUploadPhotos: false
};
