export default {
  supportBetaTemplatesList: false,
  supportBetaUsers: false,
  supportBetaUserProfile: false,
  supportBetaSettings: false,
  supportBetaLogin: false,
  supportBetaTeamCreate: false,
  supportBetaTeamEdit: false,
  supportBetaTeamView: false,
  supportBetaPropertiesList: true,
  supportBetaPropertyProfile: true,
  supportBetaPropertyCreate: true,
  supportBetaPropertyDeficient: false,
  supportBetaPropertyYardiResident: false,
  supportBetaPropertyYardiWorkOrder: false,
  supportBetaPropertyInspectionCreate: true,
  supportBetaPropertyInspectionUpdate: false,
  supportBetaPropertyInspectionMove: false,
  supportBetaPropertyUpdate: true
};
