name: Deploy

on:
  push:
    branches:
      - production
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Initiate CI/CD Repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          repository: ${{ secrets.DEPLOY_REPOSITORY }}
          event-type: push
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'